[features]
seeds = false
[programs.localnet]
mycalculatordapp = "H2QvGx7KhX1rGtJwHFaHEbULbM15srdq7onHNXhQy4qY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/secretstar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
